import { StyleSheet } from 'react-native';

import colors from '@/components/ui/colors';

export const S = StyleSheet.create({
    // ---- Header ----
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingBottom: 8,
    },
    headerBackBtn: {
        width: 36,
        height: 36,
        borderRadius: 11,
        backgroundColor: colors.primary[50],
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerCenter: { flex: 1, alignItems: 'center' },
    saveDraftBtn: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: colors.primary[50],
    },

    // ---- Step Indicator ----
    stepIndicatorWrap: { paddingHorizontal: 20, paddingBottom: 8 },
    stepIndicatorContent: { alignItems: 'center', paddingVertical: 4 },
    stepDot: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: colors.neutral[200],
        justifyContent: 'center',
        alignItems: 'center',
    },
    stepDotActive: { backgroundColor: colors.primary[600] },
    stepDotCompleted: { backgroundColor: colors.success[500] },
    stepLine: { width: 16, height: 2, backgroundColor: colors.neutral[200], marginHorizontal: 3 },
    stepLineCompleted: { backgroundColor: colors.success[400] },
    stepProgress: {
        height: 3,
        borderRadius: 2,
        backgroundColor: colors.neutral[200],
        marginTop: 8,
        overflow: 'hidden',
    },
    stepProgressFill: {
        height: '100%',
        backgroundColor: colors.primary[500],
        borderRadius: 2,
    },

    // ---- Scroll ----
    scrollContent: { paddingHorizontal: 20, paddingTop: 8 },

    // ---- Form Atoms ----
    fieldWrap: { marginBottom: 14 },
    fieldInput: {
        backgroundColor: colors.white,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
        paddingHorizontal: 14,
        height: 48,
        justifyContent: 'center',
    },
    textInput: {
        fontSize: 14,
        color: colors.primary[950],
        fontFamily: 'Inter',
        flex: 1,
    },
    chipRow: { flexDirection: 'row', gap: 8, paddingVertical: 4 },
    chipGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, paddingVertical: 4 },
    chip: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 20,
        backgroundColor: colors.white,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
    },
    chipActive: {
        backgroundColor: colors.primary[600],
        borderColor: colors.primary[600],
    },
    toggleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.neutral[100],
    },
    radioOption: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        padding: 14,
        borderRadius: 12,
        backgroundColor: colors.white,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
        marginBottom: 8,
    },
    radioOptionActive: {
        borderColor: colors.primary[400],
        backgroundColor: colors.primary[50],
    },
    radioCircle: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: colors.neutral[300],
        justifyContent: 'center',
        alignItems: 'center',
        flexShrink: 0,
    },
    radioCircleActive: { borderColor: colors.primary[500] },
    radioInner: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: colors.primary[600],
    },
    recommendedBadge: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 6,
        backgroundColor: colors.success[50],
    },
    sectionCard: {
        backgroundColor: colors.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        shadowColor: colors.primary[900],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
        borderWidth: 1,
        borderColor: colors.primary[50],
    },
    infoCard: {
        backgroundColor: colors.primary[50],
        borderRadius: 12,
        padding: 14,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.primary[100],
    },
    sectionErrorBox: {
        backgroundColor: colors.danger[50],
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: colors.danger[200],
    },
    warningBanner: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        backgroundColor: colors.warning[50],
        borderRadius: 12,
        padding: 14,
        marginBottom: 16,
        borderWidth: 1,
        borderColor: colors.warning[200],
    },
    itemCard: {
        backgroundColor: colors.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
        shadowColor: colors.primary[900],
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.04,
        shadowRadius: 8,
        elevation: 2,
    },
    hqCard: {
        borderColor: colors.primary[300],
        backgroundColor: colors.primary[50],
    },
    itemCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    itemCardBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        backgroundColor: colors.primary[100],
    },
    addButton: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingVertical: 14,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.primary[200],
        borderStyle: 'dashed',
        justifyContent: 'center',
        marginBottom: 16,
        backgroundColor: colors.primary[50],
    },
    deleteIconBtn: {
        width: 32,
        height: 32,
        borderRadius: 8,
        backgroundColor: colors.danger[50],
        justifyContent: 'center',
        alignItems: 'center',
    },
    smallAddButton: {
        paddingVertical: 8,
        alignItems: 'center',
    },
    twoColumn: {
        flexDirection: 'row',
        gap: 10,
    },
    checkboxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 12,
    },
    checkbox: {
        width: 22,
        height: 22,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: colors.neutral[300],
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkboxActive: {
        backgroundColor: colors.primary[600],
        borderColor: colors.primary[600],
    },
    dayToggleRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 4,
        borderBottomWidth: 1,
        borderBottomColor: colors.neutral[100],
    },
    dayBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
    },
    hqToggleBtn: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 8,
        backgroundColor: colors.neutral[100],
        marginRight: 8,
    },
    hqToggleBtnActive: {
        backgroundColor: colors.primary[100],
    },
    rowCenter: { flexDirection: 'row', alignItems: 'center' },
    slotRow: { flexDirection: 'row', gap: 8, alignItems: 'flex-end', marginBottom: 8 },
    previewBox: {
        backgroundColor: colors.primary[50],
        borderRadius: 10,
        padding: 12,
        marginTop: 4,
        alignItems: 'center',
    },
    logoUpload: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 14,
        padding: 16,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.primary[200],
        borderStyle: 'dashed',
        backgroundColor: colors.primary[50],
        overflow: 'hidden',
    },
    logoPlaceholder: {
        width: 56,
        height: 56,
        borderRadius: 14,
        backgroundColor: colors.primary[100],
        justifyContent: 'center',
        alignItems: 'center',
    },
    logoUploadText: {
        flex: 1,
        flexShrink: 1,
        flexBasis: 0,
        minWidth: 0,
        overflow: 'hidden',
    },
    logoOptions: {
        flexDirection: 'row',
        gap: 10,
        marginTop: 12,
    },
    logoOptionBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 12,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.primary[200],
        backgroundColor: colors.primary[50],
    },
    logoPreviewContainer: {
        alignItems: 'center',
        gap: 12,
    },
    logoImage: {
        width: 96,
        height: 96,
        borderRadius: 18,
        backgroundColor: colors.primary[50],
        borderWidth: 2,
        borderColor: colors.primary[100],
    },
    logoPreviewActions: {
        flexDirection: 'row',
        gap: 10,
        width: '100%',
    },
    logoChangeBtn: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: colors.primary[300],
        backgroundColor: colors.primary[50],
        alignItems: 'center',
    },
    logoRemoveBtn: {
        flex: 1,
        paddingVertical: 10,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: colors.danger[200],
        backgroundColor: colors.danger[50],
        alignItems: 'center',
    },
    logoPermissionError: {
        marginTop: 8,
        padding: 10,
        borderRadius: 8,
        backgroundColor: colors.danger[50],
        borderWidth: 1,
        borderColor: colors.danger[100],
    },

    // ---- Activation ----
    activationHero: {
        borderRadius: 20,
        padding: 32,
        alignItems: 'center',
        marginBottom: 16,
        overflow: 'hidden',
    },
    activationCircle1: {
        position: 'absolute', top: -30, right: -30, width: 120, height: 120,
        borderRadius: 60, backgroundColor: 'rgba(255,255,255,0.08)',
    },
    activationCircle2: {
        position: 'absolute', bottom: -20, left: -20, width: 80, height: 80,
        borderRadius: 40, backgroundColor: 'rgba(255,255,255,0.06)',
    },
    statusOption: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        padding: 14,
        borderRadius: 12,
        backgroundColor: colors.white,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
        marginBottom: 8,
    },
    statusOptionActive: {
        borderColor: colors.primary[400],
        backgroundColor: colors.primary[50],
    },
    statusDot: { width: 12, height: 12, borderRadius: 6, flexShrink: 0 },
    checklistPhase: { marginBottom: 12 },
    checklistItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 3,
    },

    // ---- Bottom CTA ----
    bottomCTA: {
        flexDirection: 'row',
        gap: 10,
        paddingHorizontal: 20,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: colors.neutral[100],
        backgroundColor: colors.white,
    },
    prevButton: {
        width: 52,
        height: 56,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: colors.primary[200],
        backgroundColor: colors.primary[50],
        justifyContent: 'center',
        alignItems: 'center',
    },
    nextBtnWrapper: {
        flex: 1,
        borderRadius: 16,
        overflow: 'hidden',
        shadowColor: colors.primary[500],
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 6,
    },
    nextBtn: {
        height: 56,
        borderRadius: 16,
        justifyContent: 'center',
        alignItems: 'center',
        flexDirection: 'row',
        gap: 8,
    },

    // ---- Country Code Picker ----
    countryCodeBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        paddingHorizontal: 10,
        paddingVertical: 10,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
        backgroundColor: colors.white,
        height: 48,
    },
    countryPickerModal: {
        flex: 1,
        backgroundColor: colors.white,
    },
    countryPickerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: colors.neutral[100],
        gap: 12,
    },
    countrySearchInput: {
        flex: 1,
        height: 40,
        backgroundColor: colors.neutral[50],
        borderRadius: 10,
        paddingHorizontal: 12,
        fontSize: 14,
        fontFamily: 'Inter',
        color: colors.primary[950],
    },
    countryItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        gap: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.neutral[50],
    },
    countryItemActive: {
        backgroundColor: colors.primary[50],
    },
    phoneInputRow: {
        flexDirection: 'row',
        gap: 8,
        alignItems: 'flex-end',
    },

    // ---- GeoFencing Modal ----
    geoModalContainer: {
        flex: 1,
        backgroundColor: '#1B2535',
    },
    geoHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: colors.white,
        gap: 12,
        zIndex: 10,
    },
    geoSearchBar: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        zIndex: 20,
        paddingHorizontal: 12,
        paddingTop: 12,
        paddingBottom: 8,
    },
    geoSearchInput: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 12,
        paddingHorizontal: 12,
        height: 48,
        gap: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 8,
    },
    geoSearchTextInput: {
        flex: 1,
        fontSize: 14,
        fontFamily: 'Inter',
        color: colors.primary[950],
    },
    geoSearchResults: {
        backgroundColor: colors.white,
        borderRadius: 12,
        marginTop: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 10,
        elevation: 8,
        overflow: 'hidden',
    },
    geoSearchResultItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 14,
        paddingVertical: 12,
        gap: 10,
        borderBottomWidth: 1,
        borderBottomColor: colors.neutral[100],
    },
    geoMapArea: {
        flex: 1,
        position: 'relative',
        justifyContent: 'center',
        alignItems: 'center',
    },
    geoCrosshair: {
        position: 'absolute',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 10,
    },
    geoMyLocationBtn: {
        position: 'absolute',
        right: 16,
        bottom: 16,
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: colors.white,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.15,
        shadowRadius: 6,
        elevation: 6,
        zIndex: 10,
    },
    geoBottomPanel: {
        backgroundColor: colors.white,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 32,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 12,
    },
    geoHandle: {
        width: 36,
        height: 4,
        borderRadius: 2,
        backgroundColor: colors.neutral[300],
        alignSelf: 'center',
        marginBottom: 16,
    },
    geoLocationDisplay: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: colors.primary[50],
        borderRadius: 10,
        padding: 12,
        marginBottom: 14,
    },
    geoRadiusRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 14,
    },
    geoRadiusChip: {
        paddingHorizontal: 12,
        paddingVertical: 7,
        borderRadius: 20,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
        backgroundColor: colors.white,
    },
    geoRadiusChipActive: {
        borderColor: colors.primary[500],
        backgroundColor: colors.primary[50],
    },
    geoShapeRow: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 16,
    },
    geoShapeBtn: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        paddingVertical: 10,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
        backgroundColor: colors.white,
    },
    geoShapeBtnActive: {
        borderColor: colors.primary[500],
        backgroundColor: colors.primary[50],
    },
    geoConfirmBtn: {
        height: 52,
        borderRadius: 14,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: colors.primary[600],
    },

    // ---- Month Picker ----
    monthGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        paddingVertical: 4,
    },
    monthCell: {
        width: '22%',
        paddingVertical: 10,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
        alignItems: 'center',
        backgroundColor: colors.white,
    },
    monthCellActive: {
        borderColor: colors.primary[500],
        backgroundColor: colors.primary[600],
    },
    monthCellStart: {
        borderColor: colors.primary[600],
        backgroundColor: colors.primary[600],
    },
    monthCellEnd: {
        borderColor: colors.accent[600],
        backgroundColor: colors.accent[600],
    },

    // ---- RazorpayX ----
    razorpayCard: {
        backgroundColor: '#F8F5FF',
        borderRadius: 14,
        padding: 16,
        marginTop: 12,
        borderWidth: 1.5,
        borderColor: '#E0D5FF',
    },
    razorpayLogo: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 10,
    },
    razorpaySectionTitle: {
        fontSize: 11,
        fontFamily: 'Inter',
        fontWeight: '700',
        color: colors.neutral[400],
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        marginTop: 14,
        marginBottom: 8,
    },
    secretInputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.white,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.neutral[200],
        paddingHorizontal: 14,
        height: 48,
    },
    eyeBtn: {
        padding: 4,
    },

    // ---- Custom facility type input ----
    customTypeInput: {
        backgroundColor: colors.white,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.primary[300],
        paddingHorizontal: 14,
        height: 44,
        marginTop: 8,
        fontSize: 14,
        fontFamily: 'Inter',
        color: colors.primary[950],
    },
    customTypeSaveBtn: {
        marginTop: 8,
        height: 40,
        borderRadius: 10,
        backgroundColor: colors.primary[600],
        justifyContent: 'center',
        alignItems: 'center',
    },
});
